version: '3'

services:

  mysqldb:
    image: mysql:5.7
    build:
      context: .
      dockerfile: ./docker/Dockerfile-mysql
    container_name: mysqldb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=typescript_db
      - MYSQL_USER=typescript
      - MYSQL_PASSWORD=123456
    ports:
     - "3306:3306"
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/:rw

  app:
    build: .
    container_name: app
    volumes:
      - ".:/app"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    depends_on:
      - mysqldb

volumes:
  my-db: